global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'dariusp123@yahoo.com'
        from: 'paraschivdarius1@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'paraschivdarius1@gmail.com'
        auth_identity: 'paraschivdarius1@gmail.com'
        auth_password: 'syzndqyxduukqcjg'